# hyprtoolkit Nord theme
# Font
font_family = Hack Nerd Font
font_family_monospace = Hack Nerd Font

# Nord theme colors
background = rgba(46, 52, 64, 0.9)
base = rgba(59,66,82,0.8)
text = rgba(229,233,240,1)
alternate_base = rgba(76,86,106,0.8)
bright_text = rgba(236,239,244,1)
accent = rgba(136,192,208,1)
accent_secondary = rgba(143,188,187,1)
